In [28]:
import numpy as np

In [29]:
a= np.array(5)
a

array(5)

In [30]:
a= np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a.reshape(3,4)

ValueError: cannot reshape array of size 15 into shape (3,4)

In [ ]:
a.shape

In [ ]:
a = a.reshape(3,5)
a

In [ ]:
print (a.shape)  
print (a.ndim)
print (a.size)
print (a.dtype)

In [ ]:
np.ones((3,4))



## some operation
    


In [37]:
 a= np.array([20,30,40,50])
 b= np.arange(4)   

In [38]:
b

array([0, 1, 2, 3])

In [39]:
a

array([20, 30, 40, 50])

In [40]:
a - b

array([20, 29, 38, 47])

In [41]:
a*b

array([  0,  30,  80, 150])

In [42]:
c=a*b

In [43]:
c>50

array([False, False,  True,  True])

In [44]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])